language: ruby
rvm:
  - 2.3
script:
  - printenv
  - gem install cfhighlander --prerelease
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then cfhighlander cfcompile ; else cfhighlander cfcompile --validate; fi